#!/usr/bin/env bash
# Install and configure Nginx on the server

apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
rm /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.html
new_string="location /redirect_me {\\nreturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4\\n}\\nlocation /"
old_string="location /"
sed -i "s|$old_string|$new_string|" /etc/nginx/sites-available/default
service nginx start
