#!/usr/bin/env bash
# Backup and compress mysql Databases
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
sudo mysqldump -u root -p"$1" --all-databases > backup.sql
tar -czf $day-$month-$year.tar.gz backup.sql
