#!/usr/bin/env bash
# This script displays "Best School" 10 times but says hi on the 9th iteraion

count=1
while(("$count" <= 10))
do
    echo "Best School"
    if [ "$count" -eq 9 ]
    then
	echo "Hi"
    fi
    ((count++))
done
