#!/usr/bin/env bash
# this script displays the number 1 to 20, indicating 4, 9 and 17 as bad luck
#+ from china, japan and italy respectively

count=1
while(("$count" <= 20))
do
     echo "$count"
     case $count in
	 4)
	     echo "bad luck from china"
	     ;;
	 9)
	     echo "bad luck from japan"
	     ;;
	 17)
	     echo "bad luck from italy"
	     ;;
     esac
     ((count++))
done
     
