#!/usr/bin/env bash
# Setup Firewall to block all incoming traffic except from port 22, 443, 80

sudo apt install ufw
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
sudo ufw enable
