#!/usr/bin/env bash
# Setup Firewall to block all incoming traffic except from port 22, 443, 80
# Forward all request to port 8080 to port 80

sudo apt install ufw -y
sudo ufw default deny incoming
sudo ufw allow 22
sudo ufw allow 443
sudo ufw allow 80
port_forwarding="*nat :PREROUTING ACCEPT [0:0]\\n-A PREROUTING -p tcp --dport 8080/tcp -j REDIRECT --to-port 80/tcp\\nCOMMIT"
sudo sed "s|COMMIT|$port_forwarding|" /etc/ufw/before.rules
sudo ufw enable
