#!/usr/bin/env bash
# redirect all traffic on port 8080 to port 80

sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80
sudo sed -i "s/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1/" /etc/sysctl.conf
sudo service ufw restart
sudo ufw enable -y
